server.port: 15000
spring.cloud.config.server.git.uri: https://github.com/OmniaService/configs.git
spring.output.ansi.enabled: 'ALWAYS'

---
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          uri: file:///A:/Programmering/Projects/Omnia/configsLocal/