server.port: 15000
spring.output.ansi.enabled: 'ALWAYS'

spring:
  profiles:
    active: native

logging:
  level:
    root: 'WARN'
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.omnia: 'DEBUG'
  pattern.console: '%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){yellow} %clr(%-5p){cyan} %clr(---){faint} %clr(%-45.45logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'

---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OmniaService/configs.git
          clone-on-start: true
          force-pull: true
          refresh-rate: 100
---
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          uri: file:..\configs
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./src/main/configs
---
spring:
  profiles: docker
  cloud:
    config:
      server:
        native:
          search-locations: file:./configs