server.port: 15000
spring.output.ansi.enabled: 'ALWAYS'

logging:
  level:
    root: 'WARN'
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.omnia: 'DEBUG'
  pattern.console: '%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){yellow} %clr(%-5p){cyan} %clr(---){faint} %clr(%-45.45logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'

---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OmniaService/configs.git
---
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/alls.INTRA/Projects/Omnia/configsLocal
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./src/main/configs