zuul:
  ignoredServices: '*'
  routes:
    user:
      path: /users/**
      serviceId: user-service
    auth:
      path: /auth/**
      service-id: auth-service
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
