spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/omnia_local?useSSL=false&serverTimezone=UTC
    username: root
    password: root